### ISSUE TITLE
Do RnD to choose a UX desigenr free

### ISSUE THREAD

**Issue by asraful** [asraful/river-hq#15]
-- mockup designer 
-- provide the list of names and recommend one to use

**Comment by tagoremithun** [comment]
RnD on UX on following link
https://docs.google.com/document/d/1UwX8q7xKNZOJ7asQJEw8Zc7DgKKFrQ3r/edit

**Comment by tagoremithun** [comment]
[RnD on choose a UX designer.docx](https://github.com/asraful/river-hq/files/8838229/RnD.on.choose.a.UX.designer.docx)
